<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
    <line>
      <![CDATA[1]]>
    </line>
    <line>
      <![CDATA[2]]>
    </line>
    <line>
      <![CDATA[3]]>
    </line>
    <line>
      <![CDATA[4]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="106" started-at="2022-02-25T07:22:47 IST" finished-at="2022-02-25T07:22:47 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="106" started-at="2022-02-25T07:22:47 IST" finished-at="2022-02-25T07:22:47 IST">
      <class name="TestNG.FailxmlCreation">
        <test-method status="PASS" signature="m1()[pri:0, instance:TestNG.FailxmlCreation@1e6d1014]" name="m1" duration-ms="16" started-at="2022-02-25T07:22:47 IST" finished-at="2022-02-25T07:22:47 IST">
          <reporter-output>
            <line>
              <![CDATA[1]]>
            </line>
          </reporter-output>
        </test-method> <!-- m1 -->
        <test-method status="FAIL" signature="m2()[pri:0, instance:TestNG.FailxmlCreation@1e6d1014]" name="m2" duration-ms="0" started-at="2022-02-25T07:22:47 IST" finished-at="2022-02-25T07:22:47 IST">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.fail(AssertJUnit.java:70)
at TestNG.FailxmlCreation.m2(FailxmlCreation.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[2]]>
            </line>
          </reporter-output>
        </test-method> <!-- m2 -->
        <test-method status="FAIL" signature="m3()[pri:0, instance:TestNG.FailxmlCreation@1e6d1014]" name="m3" duration-ms="16" started-at="2022-02-25T07:22:47 IST" finished-at="2022-02-25T07:22:47 IST">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.fail(AssertJUnit.java:70)
at TestNG.FailxmlCreation.m3(FailxmlCreation.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[3]]>
            </line>
          </reporter-output>
        </test-method> <!-- m3 -->
        <test-method status="PASS" signature="m4()[pri:0, instance:TestNG.FailxmlCreation@1e6d1014]" name="m4" duration-ms="0" started-at="2022-02-25T07:22:47 IST" finished-at="2022-02-25T07:22:47 IST">
          <reporter-output>
            <line>
              <![CDATA[4]]>
            </line>
          </reporter-output>
        </test-method> <!-- m4 -->
      </class> <!-- TestNG.FailxmlCreation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
